notebooks/track_metadata.py

I independently discovered this issue that you filed last week (b/120288024). Threw me for quite a loop until I figured out what was going on.

Truncate kernel titles longer than 50 chars

---

notebooks/deep_learning/raw/tut4_transfer_learning.ipynb
notebooks/deep_learning/raw/tut5_data_augmentation.ipynb
notebooks/lesson_preprocessor.py
notebooks/test.sh

- skip DL notebooks if untouched
- fail if notebooks were committed without running clean.py
- run render.py in CI as a sanity check (the `get_git_branch` call is still failing, but we can safely ignore it)

CI enhancements

---

Jenkinsfile
learntools/core/README.md
learntools/core/asserts.py
learntools/core/multiproblem.py
learntools/core/problem.py
learntools/core/richtext.py
learntools/embeddings/ex1_embedding_layers.py
learntools/embeddings/ex2_factorization.py
learntools/embeddings/ex3_gensim.py
learntools/pandas/creating_reading_and_writing.py
learntools/pandas/summary_functions_and_maps.py
notebooks/pandas/raw/creating-reading-and-writing-workbook.ipynb
notebooks/pandas/raw/indexing-selecting-assigning.ipynb
notebooks/python/raw/ex_1.ipynb
notebooks/test.sh

The main changes in this PR involve refactoring to the assert helpers in `core/asserts.py`, addressing a couple issues:
- ambiguity/inconsistency around how the name of the thing being tested was passed to assertion helpers and what it represented
- a bunch of assertion logic lived in `problem.py` for historical reasons, but really belonged in `asserts.py`.
I also removed a bunch of TODOs sprinkled around the code base, either because they were no longer relevant, or because they were more like an observation or explanation than an actionable item (in which case I left the comment, but removed the 'TODO' tag).
Incidentally, this made me really thankful for our CI testing. A refactor like this would have been incredibly tedious to verify without it.

Refactor assertions

---

learntools/machine_learning/ex2.py

The exercise expects `newest_home_age = 9`, but the solution shows 8

Updated solution for 2019

---

notebooks/ml_level_2/raw/cross-validation.ipynb

Cross-validation tutorial didn't have the link to go back to the main class (like in other tutorials). 
This PR adds that link, and fixes one tiny typo.

Add link back to main course and fix a typo

---

notebooks/ml_level_2/raw/xgboost.ipynb

The older link pointed to older page (https://www.kaggle.com/dansbecker/learn-machine-learning). The older page says "This Was An Early Version of Material Now Shown on Kaggle Learn"... 
The PR changes the link to the following:
https://www.kaggle.com/learn/machine-learning

Fix link to return back to course in xgboost lesson

---

notebooks/ml_level_2/raw/partial-dependence-plots.ipynb

At the end of the tutorial we point to an older link at the bottom:
Once you've done that, click **here** to return to Learning Machine Learning
The PR changes that link from 
https://www.kaggle.com/dansbecker/learn-machine-learning
to
https://www.kaggle.com/learn/machine-learning
The older page says that it is part of an "Older" tutorial.

Change a "back to course" link and fix typoes

---

learntools/machine_learning/ex3.py

Hi! While I was going through the ML exercises, I got this error:
What I had been doing was setting the variable `y` to the column *name* `SalesPrice` instead of setting it to the *column*, i.e. `y = 'SalesPrice'` instead of `y = iowa_data['SalesPrice']`. However, the error message above makes it seem that I was re-setting `home_data` to a string. Here's a fix for it.

Change `home_data` to `y` in ML ex3 SetTarget.check

---

Jenkinsfile

The Jenkins agent image preload at build time the Docker Python image.
If the Jenkins agent image doesn't have the latest released Docker Python image, this will make sure to download it and run the tests against it.

Ensure the released Docker Python image is used.

---

notebooks/feature_engineering/prod.yaml
notebooks/feature_engineering/raw/ex1.ipynb
notebooks/feature_engineering/raw/ex2.ipynb
notebooks/feature_engineering/raw/ex3.ipynb
notebooks/feature_engineering/raw/ex4.ipynb
notebooks/feature_engineering/raw/tut1.ipynb
notebooks/feature_engineering/raw/tut2.ipynb
notebooks/feature_engineering/raw/tut3.ipynb
notebooks/feature_engineering/raw/tut4.ipynb
notebooks/machine_learning/raw/tut3.ipynb

@mcleonard Couple things I think you want to do:
[] Remove your own implementation of CountEncoder with the library one.
[] Create a yaml file for the main version of these
[] After you create that yaml file, push it to Kaggle and see how it looks on Kaggle
[] Add Alexis and I as a collaborators on the test (and later the prod) version of these kaggle notebooks, so we can also push.
[] After pushing the notebooks, ask me for the exerciseIds to fill in the checking code
[] Update the exercise so each encoding is added to the previous encodings, rather than overwriting them in the variables `train_encoded` and `val_encoded`.
This is still a really long exercise. It'd be nice if we could make it quicker. One option is to provide more starter code in the SVD exercise, so the user can write …

Changes to FE tut2 and ex2. Also make other nbs more in style

---

learntools/core/problem_view.py

Running locally, the output on correct messages is now
```
<IPython.core.display.Javascript object>
Correct
```
Tested locally and on Kaggle in the ML course. We see the intended Correct message. Would like someone else to test as well (both locally and on Kaggle using a testing notebook on a different course)
Then we'll see about getting a new docker image or consider temporarily hacking this in as a Kaggle dataset.

Fix None message showing up on Correct answers

---

notebooks/feature_engineering/raw/ex3.ipynb

Some other issues I found:
1. In #5 in this notebook, the first code block has an incomplete sentence
> Returns a series with the
2. In `/notebooks/feature_engineering/raw/ex4.ipynb`, the code block right above _5) Feature Selection with Trees_ returns an error because `selected` is never defined. From looking at it though, it looks like the block was supposed to run without any modification (and `selected` should probably come from the previous block)

Fix typo in problem description

---

notebooks/test.sh

Since nbconvert 6.x, this flag is required.
`--to html` is equivalent to default option from `5.x`.

Add --to flag to nbconvert command.

---

test.sh

This will allow us to catch failures earlier than at release time.

Run the learntools test against the staging Docker image.

---

learntools/machine_learning/ex4.py

The tutorial use the same sequence of arguments as docstring says:
But the solution is not:
I see the `hint` says the order doesn't matter, but **do you use that sequence on purpose? If so, close this then. If not, there are other palces need to be changed.**

exchange mae arguments

---

notebooks/sql_advanced/raw/ex1.ipynb

The text refers to the `cbeck()` function which does not exist, from the context I assume `check()` was meant.

[General] Fix spelling mistake

---

learntools/ml_intermediate/ex1.py
notebooks/ml_intermediate/raw/ex1.ipynb

FutureWarning: Criterion 'mae' was deprecated in v1.0 and will be removed in version 1.2. Use criterion='absolute_error' which is equivalent.
https://www.kaggle.com/learn/intermediate-machine-learning/discussion/325974#1795191
https://www.kaggle.com/discussions/product-feedback/323628

[Intermediate ML] FutureWarning: Criterion 'mae' was deprecated in v1.0 

---

learntools/ml_explainability/ex3.py
notebooks/ml_explainability/raw/ex3_partial_plots.ipynb
notebooks/ml_explainability/raw/tut3_partial_plots.ipynb
notebooks/ml_explainability/track_meta.py
notebooks/test.sh

plus adding ml explainability course to testing

[ML Explainability] pdpbox no longer in docker image

---

learntools/data_cleaning/ex4.py
learntools/data_cleaning/ex5.py
notebooks/data_cleaning/raw/ex4.ipynb
notebooks/data_cleaning/raw/ex5.ipynb
notebooks/data_cleaning/raw/tut4.ipynb
notebooks/data_cleaning/raw/tut5.ipynb

- `chardet` will be removed at our next image release.
- `charset_normalizer` is a more accurate & faster than `chardet` and is a
drop-in replacement: https://pypi.org/project/charset-normalizer/

Use charset_normalizer instead of chardet.

---

notebooks/intro_to_programming/raw/ex4.ipynb

Intro to programming Lesson 4 had some missing image files. This change fixes the URLs in the exercise so that they point to the pngs. Bug: 289537275

Fix image links

---

learntools/time_series/ex3.py
learntools/time_series/ex4.py
learntools/time_series/utils.py
notebooks/feature_engineering_new/raw/tut_bonus.ipynb
notebooks/time_series/raw/tut3.ipynb

Following pandas upgrade, support for ambiguous timedelta such as `1M` and `1Y` have been dropped.

Fix utils#plot_periodogram

---

learntools/sql/ex3.py
notebooks/sql/raw/ex3.ipynb
notebooks/sql/raw/tut3.ipynb

I noticed exercise 3 in the intro to SQL tutorial was broken. The tutorial and exercise notebooks still reference the BigQuery public hacker news dataset `comments` table. This dataset has been updated and now only contains one table: `full`. 
The first query in the exercise doesn't work as nicely using the `full` table because one of the columns used is called `by` and needs to be quoted. However this PR attempts to fix the issue by referencing the correct table and adding a note in the tutorial about reserved words. 
Related discussion post on Kaggle:
https://www.kaggle.com/learn/intro-to-sql/discussion/417044#2316394
Copy of the tutorial notebook with proposed changes applied:
https://www.kaggle.com/mmcbex/sql-tutorial-3-updated
Fixes: 
https://github.com/Kaggle/learntools/issues/452
A …

SQL tutorial ex3 fixes

---

notebooks/computer_vision/track_meta.py
notebooks/deep_learning/track_meta.py
notebooks/nb_utils/track_metadata.py

Also applies original pinning type to the Computer Vision and Deep Learning tracks, which would be broken by the Keras 3 upgrade. These have already been pinned via direct DB update, but this change is needed to make sure that they don't revert back to latest during the next push.
http://b/324889848

Enable kernels to be pinned to the original docker image

---

learntools/__init__.py
learntools/core/tracking.py

This shouldn't impact any existing users, because it depends on an environment variable being set. This will enable us to rollout gradually when we're ready.  For now, there are still a few things to be done, primarily improving kagglesdk authorization.
http://b/379083750

Rough implementation using kagglesdk

---

learntools/sql/ex6.py

The SQL statements don't contain an `ORDER BY` clause, so the ordering can't be an intentional check for this exercise. This exercise happens to work most of the time because BigQuery tends to return results in the same order, but sometimes it doesn't. Learn users shouldn't have to deal with this non-determinism in the check.
http://b/415948668

Sort the results before comparison
