Kaggle/learntools

- learntools/machine_learning/kernels_metadata/ch2/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/ch3/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/ch4/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/ch5/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/ch6/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/ch7/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/tut1/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/tut2/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/tut3/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/tut4/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/tut5/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/tut6/kernel-metadata.json
- learntools/machine_learning/kernels_metadata/tut7/kernel-metadata.json
@colinmorris Does your templating system change the publication process so much that I should keep this out of master (with the intention of switching over to that in the near future)?
Either way, I'll change the URL's when we want to start pushing to the live ML track.
> Add ML kernel-metadata files

- learntools/python/blackjack.py
- learntools/python/ex3.py
- notebooks/partials/python/ex_3.ipynb
- notebooks/rendered/python/ex_3.ipynb
And set suggested number of simulations to 50k.
Interesting example of shenanigans necessary to update a question while remaining backwards compatible with old notebooks. 
I'll hold off on pushing the notebook changes until after we get a new docker build.
> update poker agent call signature

- learntools/__init__.py
- learntools/ml_explainability/nbs/ex2_perm_importance-testing.ipynb
- learntools/ml_explainability/nbs/ex2_perm_importance.ipynb
- learntools/ml_explainability/nbs/ex3_partial_plots-testing.ipynb
- learntools/ml_explainability/nbs/ex3_partial_plots.ipynb
- learntools/ml_explainability/nbs/ex4_shap_basic-testing.ipynb
- learntools/ml_explainability/nbs/ex4_shap_basic.ipynb
- learntools/ml_explainability/nbs/ex5_shap_advanced-testing.ipynb
- learntools/ml_explainability/nbs/ex5_shap_advanced.ipynb
The content of learntools/ml_insights was migrated in #28 to
learntools/ml_explainability. However, some imports were not updated.
> Fix broken imports to ml_explainability

- notebooks/data_viz_easy/track_meta.py
filled in the `course_url` in track_meta.py
> changed url

- learntools/machine_learning/ex4.py
Fix a typo from **train_x** to **train_X**
> chore: fix typo

- learntools/ml_level_2/ex7.py
- notebooks/ml_level_2/raw/ex7.ipynb
- notebooks/ml_level_2/raw/tut7.ipynb
@alexisbcook Can you check this out and give feedback?
I still need to fix the formatting of the solutions. I don't recall having it look so ugly before. But want to check that content for now.
Feel free to merge it if it looks ok. It will merge into your branch
> Update intermediate-ml ex7

- notebooks/data_viz_to_coder/track_meta.py
quick PR to fix student feedback that link to exercise was incorrect (change already pushed to kaggle site)
> one commit only

- notebooks/data_viz_to_coder/raw/tut1.ipynb
very small change to fix link to advanced data viz course
> tut1 link change

- learntools/data_viz_to_coder/ex1.py
- notebooks/data_viz_to_coder/raw/ex1.ipynb
if ex1 of new dataviz course is too long and causing attrition // shortened here! :)
- also fixed one error in notebook (that has been fixed on kaggle site)
- also some reorg to make the notebook more organized
> shortened ex1

- learntools/ml_explainability/ex4.py
> Update tutorialId in ml_explainability ex4

- learntools/data_viz_to_coder/ex3.py
- learntools/data_viz_to_coder/ex7.py
- notebooks/data_viz_to_coder/raw/ex3.ipynb
- notebooks/data_viz_to_coder/raw/ex4.ipynb
- notebooks/data_viz_to_coder/raw/tut6.ipynb
edits in response to [student feedback](https://docs.google.com/document/d/1e6LBYZrkskjWK_lnbPVqr_p3m4DdkSF7spKgTf-7ad4/edit?usp=sharing)
> dataviz fix student feedback

- notebooks/ml_intermediate/raw/tut2.ipynb
student found error - w/o random state, best approach can change
> add random state

- notebooks/ml_intermediate/raw/ex2.ipynb
> small edit

- notebooks/sql/raw/ex5.ipynb
https://www.kaggle.com/learn-forum/101576#585074
> small edits

- notebooks/feature_engineering/raw/ex3.ipynb
- notebooks/test.sh
Our automated testing wasn't running on the feature engineering course. This makes it run on that course.
> Add feature engineering course to automated testing

- learntools/feature_engineering/ex4.py
- notebooks/feature_engineering/raw/ex4.ipynb
- notebooks/feature_engineering/raw/tut4.ipynb
@dansbecker Finished up exercise 4 in the FE course. I ran Boruta on the entire dataset (it took a while) and it didn't drop any of the features.
> Finalize FE exercise 4

- learntools/feature_engineering/ex1.py
- notebooks/feature_engineering/raw/ex1.ipynb
- notebooks/feature_engineering/raw/ex2.ipynb
- notebooks/feature_engineering/raw/ex3.ipynb
- notebooks/feature_engineering/raw/ex4.ipynb
Found a solution in the checking code that was outdated. So I fixed it.
Also made formatting consistent between the exercise notebooks.
> Fix solution code and standardize formatting between notebooks

- notebooks/geospatial/raw/ex1.ipynb
- notebooks/geospatial/raw/tut1.ipynb
- notebooks/geospatial/raw/tut2.ipynb
> Small edits in geospatial course

- notebooks/machine_learning/track_meta.py
- notebooks/ml_intermediate/raw/tut1.ipynb
- notebooks/python/raw/ex_7.ipynb
change link to intro to ml course (from intermed ml)
> quick changes

- notebooks/ml_explainability/raw/tut3_partial_plots.ipynb
@alexisbcook I can't merge here any more, but this is a fix for the typo @hamelsmu pointed out.
> Fix typo in pdp tutorial

- notebooks/python/raw/ex_3.ipynb
difference between "incorrect" result and "wrong answer" unclear
> edits to wording

- learntools/pandas/summary_functions_and_maps.py
https://buganizer.corp.google.com/issues/155779266
> Pandas: remove link in hint that crashes notebook

- learntools/feature_engineering/ex3.py
- learntools/feature_engineering/ex4.py
- notebooks/feature_engineering/raw/ex2.ipynb
- notebooks/feature_engineering/raw/ex3.ipynb
- notebooks/feature_engineering/raw/ex4.ipynb
- notebooks/feature_engineering/raw/tut2.ipynb
- notebooks/feature_engineering/raw/tut3.ipynb
While working through the feature engineering course I noticed a few things here and there that I thought might be worth cleaning up. Most crucially, this fixes a bug in exercise 4 (see #229).
> Clean up a few minor issues in the feature engineering course

- learntools/data_cleaning/ex2.py
- notebooks/data_cleaning/raw/ex2.ipynb
- notebooks/data_cleaning/raw/tut2.ipynb
- ex2: removed last question 
- tut2: changed list of algorithms that need normalization
> [Data Cleaning] Lesson 2 (normalization) edits

- notebooks/nb_utils/track_metadata.py
> Always use the latest docker image for learn.

- notebooks/ml_intermediate/raw/tut1.ipynb
> [Intermediate ML] Update tut1.ipynb

- notebooks/machine_learning/setup_data.sh
- notebooks/machine_learning/track_meta.py
- notebooks/test.sh
this dataset deleted https://www.kaggle.com/pavanraj159/predicting-a-pulsar-star
> [Intro to ML] Fixing fail due to deleted dataset

- notebooks/deep_learning/raw/ex_tpus.ipynb
- notebooks/machine_learning/raw/ex_automl.ipynb
- notebooks/machine_learning/raw/tut7.ipynb
applies to:
- AutoML lesson in intro to ML course
- TPU lesson in deep learning course
> [General] Removing learntools import for zero question exercises

- notebooks/computer_vision/setup_data.sh
- notebooks/data_cleaning/setup_data.sh
- notebooks/data_viz_to_coder/setup_data.sh
- notebooks/deep_learning/setup_data.sh
- notebooks/deep_learning_intro/setup_data.sh
- notebooks/feature_engineering/setup_data.sh
- notebooks/geospatial/setup_data.sh
- notebooks/machine_learning/setup_data.sh
- notebooks/ml_intermediate/setup_data.sh
- notebooks/nlp/setup_data.sh
- notebooks/pandas/setup_data.sh
- notebooks/retry.sh
- notebooks/test.sh
The goal is to retry when we hit network flakiness.
Also standardized the setup_data.sh files.
See bug for more context.
http://b/169765584
> Add retry logic for the setup_data.sh script.

- notebooks/pandas/raw/tut_1.ipynb
Basically the mistake isn't something to do pull request for. But I saw a issue raised so I gave that person a clarification and thought maybe some people can't get over small errors and might be confused as that issue was raised in june and no one gave him answer or fixed that issue in tutorial.
> just fixed a typo error

- Jenkinsfile
> Initialize environment should load the staging image.

- learntools/data_viz_to_coder/ex3.py
simplified test for question in exercise 3
> [Data Visualization] Fixing docker fail

- README.md
- notebooks/test.sh
- test.sh
- Easily run all tests or specific tests.
- Optionally specify which image to run against.
- Add log statement to easily understand the source of the failure.
> Improve test script

- Jenkinsfile
> Post jenkins updates to Mattermost

- notebooks/test.sh
Prints the following message at the beginning of a test run:
```
Running inside image built at 20210118-122927 for commit 1e7a9242e69f8d998ca753b1734300551d8cdd52
```
This will help debug version mismatch issues @alexisbcook  reported.
> Print info about Docker image used for test run.

- notebooks/test.sh
This test is reinstalling tensorflow which is impacting other notebooks.
> Exclude game_ai ex4 from tests.

- learntools/machine_learning/ex2.py
The solution depends on the current year. And the answer 10 was correct in the previous year. But in 2021 the correct answer is 11.
> Fix hard-coded solution in HomeDescription problem

- learntools/ml_intermediate/ex3.py
- notebooks/ml_intermediate/raw/ex3.ipynb
user identified issue in learn forum
> [ML Intermediate] Fixing user-reported issue

- learntools/data_viz_to_coder/ex3.py
- notebooks/data_viz_to_coder/raw/ex3.ipynb
Please change the ending of the question from "for any platform" to "for any genre", so that it matches the answer given.
> data_viz_to_coder/ex3/step2: reword question

- learntools/data_viz_to_coder/ex3.py
- learntools/data_viz_to_coder/ex4.py
- learntools/data_viz_to_coder/ex5.py
The new Python image has matplotlib 3.4 which includes a slightly
different API for Axes management: https://github.com/matplotlib/matplotlib/releases/tag/v3.4.0
> Update checks for data_viz_to_coder track.

- notebooks/python/raw/tut_7.ipynb
I think the english grammar is not correct.
> fix typo: others -> other

- notebooks/geospatial/raw/tut2.ipynb
- notebooks/nb_utils/utils.py
error thrown
TypeError: load() missing 1 required positional argument: 'Loader'
> [General/Geospatial] Fix yaml loading issue

- notebooks/geospatial/raw/tut4.ipynb
https://www.kaggle.com/learn/geospatial-analysis/discussion/293592
> [Geospatial] Fix link to documentation

- learntools/data_cleaning/ex2.py
- notebooks/data_cleaning/raw/ex2.ipynb
- notebooks/data_cleaning/raw/tut2.ipynb
https://www.kaggle.com/learn/data-cleaning/discussion/293226
> [Data Cleaning] distplot deprecation fix

- learntools/time_series/ex4.py
- notebooks/time_series/raw/ex4.ipynb
Added a learntools install from repo in `ex4.ipynb` that we should remove after the image is updated
> Fix onpromotion feature in Exercise 4

- notebooks/game_ai/raw/tut4.ipynb
> [Intro to Game AI] update tutorial 4

- notebooks/pandas/raw/tut_2.ipynb
https://www.kaggle.com/learn/pandas/discussion/307359
> [Pandas] Fix typo in tutorial 3

- notebooks/game_ai/raw/ex4.ipynb
- notebooks/game_ai/raw/tut4.ipynb
for compatibility with stable baselines
> [Game AI] Downgrade OpenAI Gym

- notebooks/feature_engineering_new/raw/ex6.ipynb
https://www.kaggle.com/learn/feature-engineering/discussion/308813
> [Feature Engineering] Fix link to bonus lesson

- notebooks/time_series/raw/ex4.ipynb
Updating to remove a temporary patch to exercise 4.
> [Time Series] Remove pip install patch

- notebooks/test.sh
> [General] Remove NLP course from testing

- notebooks/nb_utils/lesson_preprocessor.py
> [General] Change submission instructions

- learntools/sql/ex5.py
- notebooks/sql/raw/ex5.ipynb
- notebooks/sql/track_meta.py
edits to make the courses consistent with the updated dataset
> [Intro to SQL] Updated Chicago Trips dataset

- learntools/sql_advanced/ex2.py
- notebooks/sql_advanced/raw/ex2.ipynb
- notebooks/sql_advanced/track_meta.py
still need to amend ipynb (instructions, images, pip install), turn internet on
> [Advanced SQL] edits for updated Chicago Taxi Trips dataset

- notebooks/computer_vision/raw/ex6.ipynb
- notebooks/computer_vision/raw/tut6.ipynb
https://www.kaggle.com/learn/computer-vision/discussion/386821
> [Computer Vision] A deterministic GPU implementation of AdjustContrastv2 is not currently available.

- learntools/intro_to_programming/ex3.py
fixing error in hint
https://www.kaggle.com/learn/intro-to-programming/discussion/380709
> [Intro to Programming] Error in Data Types hint

- notebooks/geospatial/raw/tut4.ipynb
> Update timeout to avoid build failures.

- Jenkinsfile
> Remove slack notifications

- Jenkinsfile
- notebooks/test.sh
- test.sh
in upgrading to keras 3, functionally of some method have changed and caused test failure. 
in the meantime, let bypass them, through running the notebooks with an older image containing the previous version of keras. until someone fixes it 
https://b.corp.google.com/issues/318672158
> Pinned selected notebooks when testing due To keras upgrade

- test.sh
should have been track
fails due to image issues
> fix test suite

- learntools/core/tracking.py
Enables Kaggle Notebooks to continue to show nudges even if using kagglesdk under the hood.
http://b/379083750
> Post response back to the outer iframe.
